image: ubuntu

stages:
  - build
    
clang-format:
  stage: build
  #only:
  #  - merge-request
  script:
    - ./scripts/clang-format-test.sh
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y cmake git findutils clang-format
