image: ubuntu

stages:
  - build
    
clang-format:
  stage: build
  #only:
  #  - merge-request
  script:
    - ln -s `which clang-format-6.0` clang-format && PATH=$PATH:$PWD ./scripts/clang-format-test.sh
  before_script:
    - apt-get update -y && apt-get install -y software-properties-common wget
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add
    - apt-add-repository -y "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y cmake git findutils clang-format-6.0

# performing the static analysis code check using a custom docker image with the llvm installation we need
code_checks:
   stage: build
   script:
     - mkdir build && cd build
     - CXX=clang++-14 cmake .. -DBUILTIN_VECCORE=ON -DROOT=OFF -DGDML=OFF -DSTATIC_ANALYSIS=ON -DBACKEND=Scalar
     - make -j8
     - ctest -j8 -V
   before_script:
     - apt update -y
     - apt install -y software-properties-common wget
     - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add
     - apt-add-repository -y "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main"
     - apt-get update -y
     - apt-get upgrade -y
     - apt install -y clang-14 libclang-14-dev clang-tidy-14 python cmake
     
# normal build against a recent ROOT; using the ALICE software stack
# because it comes fully consistent on cvmfs (including compiler etc)
with_ROOT:
   tags:
     - cvmfs
   image: cern/cc7-base
   stage: build
   script:
     - ls /cvmfs/alice.cern.ch/
     - mkdir build && cd build
       # need C++17 since ROOT was built with C++17
     - cmake .. -DBUILTIN_VECCORE=ON -DVc_DIR=${VC_ROOT}/lib/cmake -DROOT=ON -DGDML=OFF -DBACKEND=Vc
       # for the moment exclude the E03 test since downloading E03 root geometry has problems on the CI machine
     - make -j8 VERBOSE=ON && ctest --output-on-failure -j8 -E E03
   before_script:
     - echo $SHELL
     - yum install environment-modules -y
     - yum install -y unzip autoconf automake make gcc
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv CMake::v3.18.2-1)"
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv ROOT::v6-18-04-8)"
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv Vc::1.4.1-6)"

# build for USING_NAVINDEX=ON (using the cvmfs ALICE software stack: TODO: convert to project/sft...)
with_NAVINDEX:
   tags:
     - cvmfs
   image: cern/cc7-base
   stage: build
   script:
     - ls /cvmfs/alice.cern.ch/
     - mkdir build && cd build
       # need C++17 since ROOT was built with C++17
     - cmake .. -DBUILTIN_VECCORE=ON -DVc_DIR=${VC_ROOT}/lib/cmake -DUSE_NAVINDEX=ON -DROOT=ON -DGDML=OFF -DBACKEND=Vc
       # for the moment exclude the E03 test since downloading E03 root geometry has problems on the CI machine
     - make -j8 VERBOSE=ON && ctest --output-on-failure -j8 -E E03
   before_script:
     - echo $SHELL
     - yum install environment-modules -y
     - yum install -y unzip autoconf automake make gcc
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv CMake::v3.18.2-1)"
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv ROOT::v6-18-04-8)"
     - eval "$(/cvmfs/alice.cern.ch/bin/alienv printenv Vc::1.4.1-6)"
